version: '3.8'

services:
  ctfd:
    image: ctfd/ctfd:latest
    user: root
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=python:///CTFd/ctfd.db
      - REDIS_URL=redis://cache:6379/0
      - WORKERS=1
      - LOG_LEVEL=debug
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - ./plugins:/opt/CTFd/CTFd/plugins:ro
      # Essential: Mount the docker socket to allow the plugin to spawn containers
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - cache
    networks:
      - ctfd_network
      - challenge_network

  cache:
    image: redis:4-alpine
    restart: always
    volumes:
      - .data/redis:/data
    networks:
      - ctfd_network

networks:
  ctfd_network:
    driver: bridge
  challenge_network:
    driver: bridge
